### ISSUE TITLE
bi-directional synchronization

### ISSUE THREAD

**Issue by rubys** [mikemcquaid/HookHand#6]
Moved here from https://github.com/git-multimail/git-multimail/issues/109

I don't know if the final result will be a code change to HookHand, some additional docs, a separate project, or simply a conclusion that it is a bad idea.

For context, the Apache Software Foundation has a bunch of git repositories: https://git-wip-us.apache.org/repos/asf; many are mirrored here: https://github.com/apache/.

Mirroring in this case means that pushes to the asf repository cause the content to appear on github.

I'd like to make that bidirectional.  By that I mean that in addition to the above, pushes that happen to github (either explicitly or implicitly by merging pull requests) cause content to appear in the asf repository.

On a project that only sees dozens of pushes per day, where most users primarily use the same copy, where much work occurs on discrete branches, where both machines are generally up, and where synchronization is a matter of seconds; problems with be rare.  Rare, but not nonexistent.  It is important, therefore, for things to be set up to ensure that when problems occur that the appropriate people are notified so that the problems can be addressed.

If needed, I can go into more details as to why the ASF feels it needs a live copy.  I doubt I need to explain why people find the GitHub user interface attractive :-).  But I recommend that we simply take that as a given for now, and focus on what the technical challenges would be to address this.

**Comment by MikeMcQuaid** [comment]
I think that's doable but shouldn't actually require any code-changes in HookHand as you can push from the scripts that it calls. HookHand is just a system to call arbitrary scripts based on web hooks; the meat of this would have to live in the script rather than HookHand. Feel free to ask for additional clarification if any of that's unclear. Thanks!
